### ISSUE TITLE
Remove jQuery usage

### ISSUE THREAD

**Issue by ilyesrhouma** [ilyesrhouma/Saleti.net#24]
Blocked by 

- [x] Convert jQuery DataTables to an Angular-UI equivalent #16 
- [x] Use ui.bootstrap.rating for all rating components #18 
- [x] Remove dependency on bootstrap-select #22 
- [x] Use ui.bootstrap.dropdown instead of jquery bootstrap #26
