### ISSUE TITLE
Mosques search using the server API

### ISSUE THREAD

**Issue by ilyesrhouma** [ilyesrhouma/Saleti.net#33]
Blocked by

- [x] Issue #23 Make Google Maps use AngularJs
- [x] Issue #31 - Link the state and city boxes to the server API
- [x] Issue #32 - Use server API to load mosques table
